package main

import (
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"

	"github.com/lennylabs/podium/pkg/sign"
)

// captureSession spins a registry stub that records the session_id query
// param of the last request and returns the bridge plus a pointer to the
// captured value.
func captureSession(t *testing.T) (*mcpServer, *string, *httptest.Server) {
	t.Helper()
	var got string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		got = r.URL.Query().Get("session_id")
		_, _ = w.Write([]byte(`{}`))
	}))
	t.Cleanup(srv.Close)
	s := newTestServer(t, &config{registry: srv.URL, verifyPolicy: sign.PolicyNever})
	s.sessionID = "bridge-sess"
	return s, &got, srv
}

// Spec: §5 / §3.3 — the bridge threads its per-process session_id through
// every registry call so the advertised sessionCorrelation capability is
// backed (F-3.3.3). A host that did not pass session_id gets the bridge's.
func TestFetchJSON_ThreadsBridgeSession(t *testing.T) {
	t.Parallel()
	s, got, _ := captureSession(t)
	if _, err := s.fetchJSON("/v1/search_artifacts", map[string]any{"query": "x"}); err != nil {
		t.Fatalf("fetchJSON: %v", err)
	}
	if *got != "bridge-sess" {
		t.Errorf("session_id = %q, want bridge-sess", *got)
	}
	// A second call in the same process carries the same session_id.
	if _, err := s.fetchJSON("/v1/load_artifact", map[string]any{"id": "a"}); err != nil {
		t.Fatalf("fetchJSON 2: %v", err)
	}
	if *got != "bridge-sess" {
		t.Errorf("second call session_id = %q, want bridge-sess", *got)
	}
}

// A host-supplied session_id argument takes precedence over the bridge's
// (§5 "Optional session_id").
func TestFetchJSON_HostSessionIDOverrides(t *testing.T) {
	t.Parallel()
	s, got, _ := captureSession(t)
	if _, err := s.fetchJSON("/v1/load_artifact", map[string]any{"id": "a", "session_id": "host-sess"}); err != nil {
		t.Fatalf("fetchJSON: %v", err)
	}
	if *got != "host-sess" {
		t.Errorf("session_id = %q, want host-sess", *got)
	}
}

// When the bridge has no session_id (generation failed) and the host
// supplied none, no session_id is forwarded.
func TestFetchJSON_NoSessionWhenEmpty(t *testing.T) {
	t.Parallel()
	var rawQuery string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rawQuery = r.URL.RawQuery
		_, _ = w.Write([]byte(`{}`))
	}))
	t.Cleanup(srv.Close)
	s := newTestServer(t, &config{registry: srv.URL, verifyPolicy: sign.PolicyNever})
	s.sessionID = ""
	if _, err := s.fetchJSON("/v1/x", map[string]any{"q": "y"}); err != nil {
		t.Fatalf("fetchJSON: %v", err)
	}
	if strings.Contains(rawQuery, "session_id") {
		t.Errorf("query forwarded a session_id when none configured: %q", rawQuery)
	}
}

// The meta-tool handlers (here proxyGet for load_domain/search_domains)
// thread the session through fetchJSON, not just direct fetchJSON callers.
func TestProxyGet_ThreadsSession(t *testing.T) {
	t.Parallel()
	s, got, _ := captureSession(t)
	_ = s.proxyGet("/v1/load_domain", map[string]any{"path": "finance"}, nil)
	if *got != "bridge-sess" {
		t.Errorf("proxyGet session_id = %q, want bridge-sess", *got)
	}
}

// Spec: glossary "Session ID: optional UUID generated by the host per
// agent session." newSessionID returns a distinct RFC 4122 v4 UUID.
func TestNewSessionID_UUIDv4(t *testing.T) {
	t.Parallel()
	a := newSessionID()
	if _, err := url.Parse("x?session_id=" + a); err != nil {
		t.Fatalf("not URL-safe: %q", a)
	}
	if len(a) != 36 {
		t.Fatalf("len(%q) = %d, want 36", a, len(a))
	}
	if a[14] != '4' {
		t.Errorf("version nibble = %c, want 4 (%q)", a[14], a)
	}
	switch a[19] {
	case '8', '9', 'a', 'b':
	default:
		t.Errorf("variant nibble = %c, want 8/9/a/b (%q)", a[19], a)
	}
	if b := newSessionID(); b == a {
		t.Errorf("two session IDs collided: %q", a)
	}
}

// newServer populates a session ID so a freshly launched bridge correlates
// its calls.
func TestNewServer_PopulatesSessionID(t *testing.T) {
	t.Parallel()
	s, err := newServer(&config{registry: "http://example.invalid", cacheDir: t.TempDir(), cacheMode: "always-revalidate"})
	if err != nil {
		t.Fatalf("newServer: %v", err)
	}
	if s.sessionID == "" {
		t.Errorf("newServer did not populate sessionID")
	}
}
