"""Podium Python SDK — thin HTTP client over the registry API."""

from ._oauth import DeviceCodeError, Tokens
from .client import (
    BatchResult,
    Client,
    DeviceCodeRequired,
    LoadedArtifact,
    MaterializeError,
    RegistryError,
    RegistryReadOnly,
)

try:
    # Generated by setuptools-scm at build/install time. See pyproject.toml
    # → [tool.setuptools_scm]. Gitignored in source; regenerated by any
    # `pip install`.
    from ._version import __version__
except ImportError:
    __version__ = "0.0.0+unknown"

__all__ = [
    "BatchResult",
    "Client",
    "DeviceCodeError",
    "DeviceCodeRequired",
    "LoadedArtifact",
    "MaterializeError",
    "RegistryError",
    "RegistryReadOnly",
    "Tokens",
]
