"""Podium Python SDK — thin HTTP client over the registry API."""

from .client import Client, DeviceCodeRequired, RegistryError

try:
    # Generated by setuptools-scm at build/install time. See pyproject.toml
    # → [tool.setuptools_scm]. Gitignored in source; regenerated by any
    # `pip install`.
    from ._version import __version__
except ImportError:
    __version__ = "0.0.0+unknown"

__all__ = ["Client", "DeviceCodeRequired", "RegistryError"]
