// Package vectors_test generates test/vectors/delivery-record.json, the
// cross-language vectors for the §4.7.10 verification procedure and the
// §4.7.9 envelope and key rules. Each case declares its outcome in this
// package's source, written from the spec, and the generator fails when the Go
// libraries reach a different outcome, so the spec governs Go and the
// generated file governs the Python and TypeScript SDK suites, which run their
// own decoders on each case's raw bytes.
//
// Regenerate the file with UPDATE_GOLDEN=1 go test ./test/vectors/.
package vectors_test

import (
	"bytes"
	"encoding/json"
	"path/filepath"
	"reflect"
	"sort"
	"testing"

	"github.com/lennylabs/podium/internal/testharness"
	"github.com/lennylabs/podium/pkg/version"
)

// Outcome values. A case either succeeds or carries the §6.10 code its
// consumer refuses it with. No outcome names a §4.7.10 step: every refusal in
// steps 1 to 7 carries codeMismatch, and no runner can report a step.
const (
	outcomeOK       = "ok"
	codeMismatch    = "materialize.content_hash_mismatch"
	codeSigInvalid  = "materialize.signature_invalid"
	codeUnavailable = "config.signature_provider_unavailable"
)

// vectorFileName is the generated file, beside this package's source.
const vectorFileName = "delivery-record.json"

// vectorFile is the layout of delivery-record.json. Every section is sorted
// by case name.
type vectorFile struct {
	Description   string           `json:"description"`
	SigningSeed   string           `json:"signing_seed_hex"`
	PublicKey     string           `json:"public_key"`
	Responses     []responseVector `json:"responses"`
	Batch         []batchVector    `json:"batch"`
	Base64        []base64Vector   `json:"base64"`
	Envelope      []envelopeVector `json:"envelope"`
	ManifestBody  []manifestVector `json:"manifest_body"`
	VerifyKeyList []keySetVector   `json:"verify_key_list"`
	KeyFile       []keySetVector   `json:"key_file"`
}

// fileDescription is the description member of the generated file.
const fileDescription = "Cross-language vectors for the §4.7.10 delivery-record " +
	"verification procedure and the §4.7.9 envelope and key rules. Generated by " +
	"test/vectors/vectors_test.go; regenerate with UPDATE_GOLDEN=1 go test ./test/vectors/. " +
	"Byte values are standard base64. Every delivery_signature in a response or batch " +
	"body is signed by the key of signing_seed_hex, whose public key is public_key."

// TestDeliveryVectors_MatchGo builds every vector case, asserts that the Go
// libraries reach each case's declared outcome, and compares the generated
// file with test/vectors/delivery-record.json.
//
// Spec: §4.7.10
// Spec: §4.7.9
func TestDeliveryVectors_MatchGo(t *testing.T) {
	t.Parallel()
	file := vectorFile{
		Description:   fileDescription,
		SigningSeed:   seedAHex,
		PublicKey:     keyB64(publicKey(seedAHex)),
		Responses:     responseVectors(t),
		Batch:         batchVectors(t),
		Base64:        base64Vectors(t),
		Envelope:      envelopeVectors(t),
		ManifestBody:  manifestVectors(t),
		VerifyKeyList: verifyKeyListVectors(t),
		KeyFile:       keyFileVectors(t),
	}
	if t.Failed() {
		return
	}
	testharness.AssertGoldenFile(t, filepath.Join(".", vectorFileName), encodeVectors(t, file))
}

// encodeVectors marshals the file with two-space indentation, no HTML
// escaping, and a trailing newline, so a regeneration that changes no case
// rewrites identical bytes.
func encodeVectors(t testing.TB, file vectorFile) []byte {
	t.Helper()
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(file); err != nil {
		t.Fatalf("encode vectors: %v", err)
	}
	return buf.Bytes()
}

// sortedKeys returns the keys of m in ascending byte order.
func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// sortByName sorts a section by the name each case carries.
func sortByName[T any](cases []T, name func(T) string) []T {
	sort.SliceStable(cases, func(i, j int) bool { return name(cases[i]) < name(cases[j]) })
	return cases
}

// checkUniqueNames fails the test when two cases of one section share a name,
// because the SDK runners report a case by its name.
func checkUniqueNames(t testing.TB, section string, names []string) {
	t.Helper()
	seen := map[string]bool{}
	for _, n := range names {
		if seen[n] {
			t.Errorf("%s: case name %q is used twice", section, n)
		}
		seen[n] = true
	}
}

// checkRecord fails the test unless got, the record a parser yielded, equals
// want, the record the case declares. A nil and an empty resource map are the
// same record.
func checkRecord(t testing.TB, where string, got, want version.DeliveryRecord) {
	t.Helper()
	if len(got.Resources) == 0 {
		got.Resources = nil
	}
	if len(want.Resources) == 0 {
		want.Resources = nil
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("%s: parsed record\n  %#v\nwant the declared record\n  %#v", where, got, want)
	}
}
