package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/lennylabs/podium/pkg/objectstore"
	"github.com/lennylabs/podium/pkg/store"
)

// adminMigrateToStandard pumps the standalone deployment's state
// (SQLite metadata + filesystem object store) into a standard
// deployment (Postgres + S3).
//
// The command copies what the existing Store / objectstore SPIs
// expose: tenants, manifests, layer configs, and content blobs.
// Audit logs are copied byte-for-byte. Dependency edges are
// regenerated by the next ingest. Admin grants are not pumped
// (the Store interface lacks ListAdmins); operators re-issue them
// after migration.
//
// Usage:
//
//	podium admin migrate-to-standard \
//	  --source-sqlite path/to/podium.db \
//	  --source-objects path/to/objects \
//	  --target-postgres-dsn postgres://... \
//	  --target-s3-endpoint host:port \
//	  --target-s3-bucket podium \
//	  [--source-audit-log path/to/audit.log] \
//	  [--target-audit-log path/to/audit.log] \
//	  [--target-store sqlite --target-sqlite path/to/dest.db] \
//	  [--target-objects path/to/dest/objects] \
//	  [--dry-run]
func adminMigrateToStandard(args []string) int {
	fs := flag.NewFlagSet("admin migrate-to-standard", flag.ContinueOnError)
	setUsage(fs, "Pump standalone state (SQLite + filesystem) into a standard deployment (Postgres + S3).")
	srcSQLite := fs.String("source-sqlite", "", "source SQLite path (required)")
	srcObjects := fs.String("source-objects", "", "source filesystem object store path")
	srcAudit := fs.String("source-audit-log", "", "source audit log file (optional)")
	targetStore := fs.String("target-store", "postgres", "target metadata store: postgres | sqlite")
	targetPostgresDSN := fs.String("target-postgres-dsn", "", "target Postgres DSN")
	targetSQLite := fs.String("target-sqlite", "", "target SQLite path (when --target-store=sqlite)")
	targetObjectsType := fs.String("target-objects-type", "filesystem", "target object store: filesystem | s3")
	targetObjects := fs.String("target-objects", "", "target filesystem object store path")
	targetS3Endpoint := fs.String("target-s3-endpoint", "", "target S3 endpoint (host:port)")
	targetS3Bucket := fs.String("target-s3-bucket", "", "target S3 bucket")
	targetS3Region := fs.String("target-s3-region", "us-east-1", "target S3 region")
	targetS3AccessKey := fs.String("target-s3-access-key-id", "", "target S3 access key id")
	targetS3SecretKey := fs.String("target-s3-secret-access-key", "", "target S3 secret access key")
	targetAudit := fs.String("target-audit-log", "", "target audit log file (optional)")
	dryRun := fs.Bool("dry-run", false, "report what would migrate; touch nothing")
	fs.SetOutput(os.Stderr)
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *srcSQLite == "" {
		fmt.Fprintln(os.Stderr, "error: --source-sqlite is required")
		return 2
	}
	if *targetStore == "postgres" && *targetPostgresDSN == "" {
		fmt.Fprintln(os.Stderr, "error: --target-postgres-dsn is required when --target-store=postgres")
		return 2
	}
	if *targetStore == "sqlite" && *targetSQLite == "" {
		fmt.Fprintln(os.Stderr, "error: --target-sqlite is required when --target-store=sqlite")
		return 2
	}

	plan, err := planMigration(*srcSQLite)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	fmt.Printf("source plan:\n  tenants:       %d\n  manifests:     %d\n  layer configs: %d\n",
		len(plan.tenants), plan.manifestCount, plan.layerCount)

	if *dryRun {
		fmt.Println("(dry-run; nothing migrated)")
		return 0
	}

	target, closer, err := openTargetStore(*targetStore, *targetPostgresDSN, *targetSQLite)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: open target store: %v\n", err)
		return 1
	}
	defer closer()

	if err := pumpStore(plan, target); err != nil {
		fmt.Fprintf(os.Stderr, "error: pump store: %v\n", err)
		return 1
	}
	fmt.Println("metadata migration complete")

	if *srcObjects != "" {
		copied, err := pumpObjects(*srcObjects, *targetObjectsType, *targetObjects, objectstore.S3Config{
			Endpoint:        *targetS3Endpoint,
			Bucket:          *targetS3Bucket,
			Region:          *targetS3Region,
			AccessKeyID:     *targetS3AccessKey,
			SecretAccessKey: *targetS3SecretKey,
			UseSSL:          true,
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: pump objects: %v\n", err)
			return 1
		}
		fmt.Printf("object migration complete (%d blob(s))\n", copied)
	}

	if *srcAudit != "" && *targetAudit != "" {
		if err := copyFile(*srcAudit, *targetAudit); err != nil {
			fmt.Fprintf(os.Stderr, "error: copy audit log: %v\n", err)
			return 1
		}
		fmt.Println("audit log copied")
	}
	return 0
}

type migrationPlan struct {
	tenants       []store.Tenant
	manifests     map[string][]store.ManifestRecord
	layerConfigs  map[string][]store.LayerConfig
	manifestCount int
	layerCount    int
}

// planMigration opens the SQLite source and pumps every tenant
// the standalone bootstrap creates ("default"), reading manifests
// and layer configs into memory. The full enumeration is
// deliberate; the standalone deployment is small enough that the
// dataset fits in memory.
func planMigration(sqlitePath string) (*migrationPlan, error) {
	src, err := store.OpenSQLite(sqlitePath)
	if err != nil {
		return nil, fmt.Errorf("open source SQLite: %w", err)
	}
	plan := &migrationPlan{
		manifests:    map[string][]store.ManifestRecord{},
		layerConfigs: map[string][]store.LayerConfig{},
	}
	// Standalone has one tenant. Future multi-tenant migration
	// passes plug a ListTenants implementation here.
	for _, id := range []string{"default"} {
		t, err := src.GetTenant(context.Background(), id)
		if err != nil {
			continue
		}
		plan.tenants = append(plan.tenants, t)
		manifests, err := src.ListManifests(context.Background(), id)
		if err != nil {
			return nil, fmt.Errorf("list manifests for %s: %w", id, err)
		}
		plan.manifests[id] = manifests
		plan.manifestCount += len(manifests)

		layers, err := src.ListLayerConfigs(context.Background(), id)
		if err != nil {
			return nil, fmt.Errorf("list layer configs for %s: %w", id, err)
		}
		plan.layerConfigs[id] = layers
		plan.layerCount += len(layers)
	}
	return plan, nil
}

func openTargetStore(kind, postgresDSN, sqlitePath string) (store.Store, func(), error) {
	switch kind {
	case "postgres":
		s, err := store.OpenPostgres(postgresDSN)
		return s, func() {}, err
	case "sqlite":
		_ = os.MkdirAll(filepath.Dir(sqlitePath), 0o755)
		s, err := store.OpenSQLite(sqlitePath)
		return s, func() {}, err
	}
	return nil, func() {}, fmt.Errorf("unknown target store: %s", kind)
}

func pumpStore(plan *migrationPlan, target store.Store) error {
	ctx := context.Background()
	for _, t := range plan.tenants {
		_ = target.CreateTenant(ctx, t)
	}
	for tenantID, manifests := range plan.manifests {
		for _, m := range manifests {
			if err := target.PutManifest(ctx, m); err != nil {
				return fmt.Errorf("put manifest %s/%s: %w", tenantID, m.ArtifactID, err)
			}
		}
	}
	for tenantID, layers := range plan.layerConfigs {
		for _, l := range layers {
			if err := target.PutLayerConfig(ctx, l); err != nil {
				return fmt.Errorf("put layer config %s/%s: %w", tenantID, l.ID, err)
			}
		}
	}
	return nil
}

// pumpObjects walks the filesystem-backed source object store and
// copies every blob into the target backend.
func pumpObjects(srcRoot, targetType, targetRoot string, s3 objectstore.S3Config) (int, error) {
	target, err := openTargetObjectStore(targetType, targetRoot, s3)
	if err != nil {
		return 0, err
	}
	ctx := context.Background()
	count := 0
	err = filepath.Walk(srcRoot, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil || info == nil || info.IsDir() {
			return walkErr
		}
		key, err := filepath.Rel(srcRoot, path)
		if err != nil {
			return err
		}
		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := target.Put(ctx, filepath.ToSlash(key), body, ""); err != nil {
			return fmt.Errorf("put %s: %w", key, err)
		}
		count++
		return nil
	})
	return count, err
}

func openTargetObjectStore(kind, root string, s3 objectstore.S3Config) (objectstore.Provider, error) {
	switch kind {
	case "filesystem":
		_ = os.MkdirAll(root, 0o755)
		return objectstore.Open(root)
	case "s3":
		return objectstore.NewS3(s3)
	}
	return nil, fmt.Errorf("unknown target object store: %s", kind)
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}
