package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/lennylabs/podium/pkg/objectstore"
	"github.com/lennylabs/podium/pkg/store"
)

// adminMigrateToStandard pumps the standalone deployment's state
// (SQLite metadata + filesystem object store) into a standard
// deployment (Postgres + S3).
//
// The command copies what the existing Store / objectstore SPIs
// expose: tenants, manifests, layer configs, admin grants, and content
// blobs. Audit logs are copied byte-for-byte. Dependency edges are
// regenerated by the next ingest.
//
// The §13.10 / §13.11.6 short form is
//
//	podium admin migrate-to-standard --postgres <dsn> --object-store <url>
//
// where --object-store is either a filesystem path (file:///path or a
// bare path) or an S3 URL (s3://[key:secret@]endpoint/bucket[?region=R][&ssl=false]).
// Source flags default to the standalone layout under ~/.podium so the
// short form runs verbatim on a standalone host. The granular
// --target-* flags remain as overrides for advanced S3 configuration.
//
// Usage:
//
//	podium admin migrate-to-standard \
//	  --postgres postgres://... \
//	  --object-store s3://minio:9000/podium \
//	  [--source-sqlite path/to/podium.db] \
//	  [--source-objects path/to/objects] \
//	  [--source-audit-log path/to/audit.log --target-audit-log path/to/audit.log] \
//	  [--dry-run]
func adminMigrateToStandard(args []string) int {
	fs := flag.NewFlagSet("admin migrate-to-standard", flag.ContinueOnError)
	setUsage(fs, "Pump standalone state (SQLite + filesystem) into a standard deployment (Postgres + S3).")
	// §13.4 short form: --postgres / --object-store.
	postgres := fs.String("postgres", "", "target Postgres DSN (§13.4 short form; implies --target-store=postgres)")
	objectStore := fs.String("object-store", "", "target object store URL: file:///path or s3://[key:secret@]endpoint/bucket[?region=R&ssl=false] (§13.4 short form)")
	srcSQLite := fs.String("source-sqlite", "", "source SQLite path (default ~/.podium/standalone/podium.db)")
	srcObjects := fs.String("source-objects", "", "source filesystem object store path (default ~/.podium/standalone/objects)")
	srcAudit := fs.String("source-audit-log", "", "source audit log file (default ~/.podium/audit.log)")
	targetStore := fs.String("target-store", "postgres", "target metadata store: postgres | sqlite")
	targetPostgresDSN := fs.String("target-postgres-dsn", "", "target Postgres DSN (override for --postgres)")
	targetSQLite := fs.String("target-sqlite", "", "target SQLite path (when --target-store=sqlite)")
	targetObjectsType := fs.String("target-objects-type", "filesystem", "target object store: filesystem | s3")
	targetObjects := fs.String("target-objects", "", "target filesystem object store path")
	targetS3Endpoint := fs.String("target-s3-endpoint", "", "target S3 endpoint (host:port)")
	targetS3Bucket := fs.String("target-s3-bucket", "", "target S3 bucket")
	targetS3Region := fs.String("target-s3-region", "us-east-1", "target S3 region")
	targetS3AccessKey := fs.String("target-s3-access-key-id", "", "target S3 access key id")
	targetS3SecretKey := fs.String("target-s3-secret-access-key", "", "target S3 secret access key")
	targetS3UseSSL := fs.Bool("target-s3-use-ssl", true, "target S3 uses TLS")
	targetAudit := fs.String("target-audit-log", "", "target audit log file (optional)")
	dryRun := fs.Bool("dry-run", false, "report what would migrate; touch nothing")
	fs.SetOutput(os.Stderr)
	if err := fs.Parse(args); err != nil {
		return parseExit(err)
	}

	// §13.4 short-form flags fold into the granular target flags.
	if *postgres != "" {
		*targetStore = "postgres"
		*targetPostgresDSN = *postgres
	}
	if *objectStore != "" {
		kind, fsRoot, s3, err := parseObjectStoreURL(*objectStore, *targetS3Region, *targetS3AccessKey, *targetS3SecretKey, *targetS3UseSSL)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: --object-store: %v\n", err)
			return 2
		}
		*targetObjectsType = kind
		switch kind {
		case "filesystem":
			*targetObjects = fsRoot
		case "s3":
			*targetS3Endpoint = s3.Endpoint
			*targetS3Bucket = s3.Bucket
			*targetS3Region = s3.Region
			*targetS3AccessKey = s3.AccessKeyID
			*targetS3SecretKey = s3.SecretAccessKey
			*targetS3UseSSL = s3.UseSSL
		}
	}

	// Source defaults follow the standalone layout (§13.10) so the
	// short form runs verbatim on a standalone host. Objects and the
	// audit log default only when the standalone path is present, so a
	// deployment without them is not forced to a failure.
	home, _ := os.UserHomeDir()
	// Default the source SQLite path only when the standalone DB actually
	// exists, mirroring the objects/audit defaults below. Otherwise an absent
	// --source-sqlite is reported as required (exit 2) rather than silently
	// pointing at a non-existent default.
	if *srcSQLite == "" && home != "" {
		def := filepath.Join(home, ".podium", "standalone", "podium.db")
		if fi, err := os.Stat(def); err == nil && !fi.IsDir() {
			*srcSQLite = def
		}
	}
	if *srcObjects == "" && home != "" {
		def := filepath.Join(home, ".podium", "standalone", "objects")
		if fi, err := os.Stat(def); err == nil && fi.IsDir() {
			*srcObjects = def
		}
	}
	if *srcAudit == "" && home != "" {
		def := filepath.Join(home, ".podium", "audit.log")
		if fi, err := os.Stat(def); err == nil && !fi.IsDir() {
			*srcAudit = def
		}
	}

	// Validate the source first so a bare invocation reports the source
	// requirement (the standalone DB) before the target requirements.
	if *srcSQLite == "" {
		fmt.Fprintln(os.Stderr, "error: --source-sqlite is required")
		return 2
	}
	if *targetStore == "postgres" && *targetPostgresDSN == "" {
		fmt.Fprintln(os.Stderr, "error: --target-postgres-dsn is required when --target-store=postgres")
		return 2
	}
	if *targetStore == "sqlite" && *targetSQLite == "" {
		fmt.Fprintln(os.Stderr, "error: --target-sqlite is required when --target-store=sqlite")
		return 2
	}

	plan, err := planMigration(*srcSQLite)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	fmt.Printf("source plan:\n  tenants:       %d\n  manifests:     %d\n  layer configs: %d\n  admin grants:  %d\n",
		len(plan.tenants), plan.manifestCount, plan.layerCount, plan.adminCount)

	if *dryRun {
		fmt.Println("(dry-run; nothing migrated)")
		return 0
	}

	target, closer, err := openTargetStore(*targetStore, *targetPostgresDSN, *targetSQLite)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: open target store: %v\n", err)
		return 1
	}
	defer closer()

	if err := pumpStore(plan, target); err != nil {
		fmt.Fprintf(os.Stderr, "error: pump store: %v\n", err)
		return 1
	}
	fmt.Printf("metadata migration complete (%d admin grant(s) preserved)\n", plan.adminCount)

	// Migrate objects only when a target object destination is configured. A
	// filesystem target needs a root and an s3 target needs a bucket; without
	// one (for example a metadata-only sqlite→sqlite migration) there is
	// nowhere to copy blobs, so skip rather than fail on an empty root.
	objectsTargetSet := (*targetObjectsType == "filesystem" && *targetObjects != "") ||
		(*targetObjectsType == "s3" && *targetS3Bucket != "")
	if *srcObjects != "" && !objectsTargetSet {
		fmt.Fprintln(os.Stderr, "note: source objects found but no target object store configured (--object-store / --target-objects); skipping object migration")
	}
	if *srcObjects != "" && objectsTargetSet {
		copied, err := pumpObjects(*srcObjects, *targetObjectsType, *targetObjects, objectstore.S3Config{
			Endpoint:        *targetS3Endpoint,
			Bucket:          *targetS3Bucket,
			Region:          *targetS3Region,
			AccessKeyID:     *targetS3AccessKey,
			SecretAccessKey: *targetS3SecretKey,
			UseSSL:          *targetS3UseSSL,
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: pump objects: %v\n", err)
			return 1
		}
		fmt.Printf("object migration complete (%d blob(s))\n", copied)
	}

	// §13.10 lists audit history among the preserved state. Copy it
	// when a target sink is named; otherwise warn loudly rather than
	// completing silently with the history left behind (§13.4 audit
	// preservation is not silent).
	if *srcAudit != "" {
		if *targetAudit != "" {
			if err := copyFile(*srcAudit, *targetAudit); err != nil {
				fmt.Fprintf(os.Stderr, "error: copy audit log: %v\n", err)
				return 1
			}
			fmt.Println("audit log copied")
		} else {
			fmt.Fprintf(os.Stderr,
				"warning: audit history at %s was NOT copied; pass --target-audit-log to preserve it (§13.10)\n",
				*srcAudit)
		}
	}
	return 0
}

// parseObjectStoreURL parses the §13.4 --object-store short form into a
// target object-store kind and config. A bare path or a file:// URL maps
// to the filesystem backend; an s3:// URL maps to S3, taking the
// endpoint from the host, the bucket from the first path segment,
// credentials from optional userinfo, and the region / TLS toggle from
// the query string. Region, credentials, and TLS fall back to the passed
// defaults when the URL omits them.
func parseObjectStoreURL(raw, region, accessKey, secretKey string, useSSL bool) (kind, fsRoot string, s3 objectstore.S3Config, err error) {
	u, perr := url.Parse(raw)
	if perr != nil {
		return "", "", objectstore.S3Config{}, perr
	}
	switch u.Scheme {
	case "", "file":
		// file:///abs/path -> u.Path; bare /abs/path -> u.Path too.
		root := u.Path
		if root == "" {
			root = raw
		}
		return "filesystem", root, objectstore.S3Config{}, nil
	case "s3":
		if u.Host == "" {
			return "", "", objectstore.S3Config{}, fmt.Errorf("s3 url %q has no endpoint host", raw)
		}
		bucket := strings.Trim(u.Path, "/")
		if bucket == "" {
			return "", "", objectstore.S3Config{}, fmt.Errorf("s3 url %q has no bucket path", raw)
		}
		q := u.Query()
		if r := q.Get("region"); r != "" {
			region = r
		}
		if ssl := q.Get("ssl"); ssl != "" {
			useSSL = ssl != "false" && ssl != "0"
		}
		if u.User != nil {
			accessKey = u.User.Username()
			if p, ok := u.User.Password(); ok {
				secretKey = p
			}
		}
		return "s3", "", objectstore.S3Config{
			Endpoint:        u.Host,
			Bucket:          bucket,
			Region:          region,
			AccessKeyID:     accessKey,
			SecretAccessKey: secretKey,
			UseSSL:          useSSL,
		}, nil
	}
	return "", "", objectstore.S3Config{}, fmt.Errorf("unsupported object-store scheme %q (use file:// or s3://)", u.Scheme)
}

type migrationPlan struct {
	tenants       []store.Tenant
	manifests     map[string][]store.ManifestRecord
	layerConfigs  map[string][]store.LayerConfig
	adminGrants   map[string][]store.AdminGrant
	manifestCount int
	layerCount    int
	adminCount    int
}

// planMigration opens the SQLite source and pumps every tenant
// the standalone bootstrap creates ("default"), reading manifests
// and layer configs into memory. The full enumeration is
// deliberate; the standalone deployment is small enough that the
// dataset fits in memory.
func planMigration(sqlitePath string) (*migrationPlan, error) {
	src, err := store.OpenSQLite(sqlitePath)
	if err != nil {
		return nil, fmt.Errorf("open source SQLite: %w", err)
	}
	plan := &migrationPlan{
		manifests:    map[string][]store.ManifestRecord{},
		layerConfigs: map[string][]store.LayerConfig{},
		adminGrants:  map[string][]store.AdminGrant{},
	}
	// Standalone has one tenant. Future multi-tenant migration
	// passes plug a ListTenants implementation here.
	for _, id := range []string{"default"} {
		t, err := src.GetTenant(context.Background(), id)
		if err != nil {
			continue
		}
		plan.tenants = append(plan.tenants, t)
		manifests, err := src.ListManifests(context.Background(), id)
		if err != nil {
			return nil, fmt.Errorf("list manifests for %s: %w", id, err)
		}
		plan.manifests[id] = manifests
		plan.manifestCount += len(manifests)

		layers, err := src.ListLayerConfigs(context.Background(), id)
		if err != nil {
			return nil, fmt.Errorf("list layer configs for %s: %w", id, err)
		}
		plan.layerConfigs[id] = layers
		plan.layerCount += len(layers)

		// §13.10: "admin grants ... are preserved". Enumerate the
		// source grants so pumpStore can re-issue them on the target.
		grants, err := src.ListAdminGrants(context.Background(), id)
		if err != nil {
			return nil, fmt.Errorf("list admin grants for %s: %w", id, err)
		}
		plan.adminGrants[id] = grants
		plan.adminCount += len(grants)
	}
	return plan, nil
}

func openTargetStore(kind, postgresDSN, sqlitePath string) (store.Store, func(), error) {
	switch kind {
	case "postgres":
		s, err := store.OpenPostgres(postgresDSN)
		return s, func() {}, err
	case "sqlite":
		_ = os.MkdirAll(filepath.Dir(sqlitePath), 0o755)
		s, err := store.OpenSQLite(sqlitePath)
		return s, func() {}, err
	}
	return nil, func() {}, fmt.Errorf("unknown target store: %s", kind)
}

func pumpStore(plan *migrationPlan, target store.Store) error {
	ctx := context.Background()
	for _, t := range plan.tenants {
		_ = target.CreateTenant(ctx, t)
	}
	for tenantID, manifests := range plan.manifests {
		for _, m := range manifests {
			if err := target.PutManifest(ctx, m); err != nil {
				return fmt.Errorf("put manifest %s/%s: %w", tenantID, m.ArtifactID, err)
			}
		}
	}
	for tenantID, layers := range plan.layerConfigs {
		for _, l := range layers {
			if err := target.PutLayerConfig(ctx, l); err != nil {
				return fmt.Errorf("put layer config %s/%s: %w", tenantID, l.ID, err)
			}
		}
	}
	for tenantID, grants := range plan.adminGrants {
		for _, g := range grants {
			if err := target.GrantAdmin(ctx, g); err != nil {
				return fmt.Errorf("grant admin %s/%s: %w", tenantID, g.UserID, err)
			}
		}
	}
	return nil
}

// pumpObjects walks the filesystem-backed source object store and
// copies every blob into the target backend.
func pumpObjects(srcRoot, targetType, targetRoot string, s3 objectstore.S3Config) (int, error) {
	target, err := openTargetObjectStore(targetType, targetRoot, s3)
	if err != nil {
		return 0, err
	}
	ctx := context.Background()
	count := 0
	err = filepath.Walk(srcRoot, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil || info == nil || info.IsDir() {
			return walkErr
		}
		key, err := filepath.Rel(srcRoot, path)
		if err != nil {
			return err
		}
		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := target.Put(ctx, filepath.ToSlash(key), body, ""); err != nil {
			return fmt.Errorf("put %s: %w", key, err)
		}
		count++
		return nil
	})
	return count, err
}

func openTargetObjectStore(kind, root string, s3 objectstore.S3Config) (objectstore.Provider, error) {
	switch kind {
	case "filesystem":
		_ = os.MkdirAll(root, 0o755)
		return objectstore.Open(root)
	case "s3":
		return objectstore.NewS3(s3)
	}
	return nil, fmt.Errorf("unknown target object store: %s", kind)
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}
